create table t_fields
(
    id   int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table t_orders
(
    id            int8 generated by default as identity,
    content       varchar(255) not null,
    created_at    timestamp    not null,
    deadline      timestamp    not null,
    is_active     boolean      not null,
    status        varchar(255),
    title         varchar(255) not null,
    client_id     int8         not null,
    contractor_id int8,
    field_id      int8,
    primary key (id)
);

create table t_fields_orders
(
    field_model_id int8 not null,
    orders_id      int8 not null
);

create table t_roles
(
    id   int8 generated by default as identity,
    role varchar(255) not null,
    primary key (id)
);

create table t_users
(
    id         int8 generated by default as identity,
    is_blocked boolean      not null,
    name       varchar(255) not null,
    password   varchar(255) not null,
    surname    varchar(255) not null,
    username   varchar(255) not null,
    primary key (id)
);

create table t_users_roles
(
    user_model_id int8 not null,
    roles_id      int8 not null
);
