create table if not exists t_roles
(
    id   bigint generated by default as identity
        primary key,
    role varchar(255) not null
        constraint uk_gt1wao0paa02bgmd9sp4xrlb4
            unique
);

create table if not exists t_users
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255) not null
        constraint uk_1f8qpknpngd98342v0j2ceadc
            unique,
    is_blocked boolean      not null,
    name       varchar(255) not null,
    password   varchar(255) not null,
    phone      varchar(255) not null
        constraint uk_orgokccclv1b5cl8h5jiw9bif
            unique,
    surname    varchar(255) not null,
    username   varchar(255) not null
        constraint uk_sp0e01od15gf4nu5ffu87qb9n
            unique
);

create table if not exists t_fields
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint uk_gc30oe4nfepo74bwy44a9njuk
            unique
);

create table if not exists t_orders
(
    id            bigint generated by default as identity
        primary key,
    content       varchar(255) not null
        constraint uk_19kbe2k1droujml4we9658g1n
            unique,
    created_at    timestamp    not null,
    deadline      timestamp    not null,
    is_active     boolean      not null,
    price         integer      not null,
    status        varchar(255),
    title         varchar(255) not null
        constraint uk_2sd4rqeynwmgpq02pnp96c833
            unique,
    client_id     bigint       not null
        constraint fkobysho36ubfnwrhi57hdof1u8
            references t_users,
    contractor_id bigint
        constraint fkcmwr27wlsgabuw9tkgqysd38t
            references t_users,
    field_id      bigint
        constraint fk4tb2gugn3kul619cboy9vejem
            references t_fields
);

create table if not exists t_proposals
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp not null,
    proposed_price integer   not null,
    candidate_id   bigint    not null
        constraint fkkwaa43wl32i34jspdw32smsy8
            references t_users,
    order_id       bigint    not null
        constraint fkk9u4ljrmwmif7td14pdqkhke2
            references t_orders
);

create table if not exists t_fields_orders
(
    field_model_id bigint not null
        constraint fk2qm32c5kbbf13xp5o9b6b4rj9
            references t_fields,
    orders_id      bigint not null
        constraint uk_tiummaxhxuaavxkxht6lhqarf
            unique
        constraint fkai92n82vogkr0ynav9ti8w0xl
            references t_orders
);

create table if not exists t_orders_proposals
(
    order_model_id bigint not null
        constraint fksap65t8aq4c9cgarcwy131td2
            references t_orders,
    proposals_id   bigint not null
        constraint uk_i4ntyhae8nufjpru6hqm2u2to
            unique
        constraint fkarquaccjkl2luo7r0xwrm26tc
            references t_proposals
);

create table if not exists t_users_roles
(
    user_model_id bigint not null
        constraint fkhry36cf5flp5kd0unjjboplyj
            references t_users,
    roles_id      bigint not null
        constraint fk9qf4n9htwf2hlfnqoucqmyeg9
            references t_roles
);
