create table t_proposals
(
    id             int8 generated by default as identity,
    created_at     timestamp not null,
    proposed_price int4      not null,
    candidate_id   int8      not null,
    order_id       int8      not null,
    primary key (id)
);

create table t_orders_proposals
(
    order_model_id int8 not null,
    proposals_id   int8 not null
)